### ISSUE TITLE
More advanced helpers for fetching

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQCoreDataKit#11]
See [MagicalRecord](https://github.com/magicalpanda/MagicalRecord) for ideas, but make things *Swifter*.

**Comment by artemkalinovsky** [comment]
Hi Jesse,

Yesterday I started to work on https://github.com/jessesquires/JSQCoreDataKit/issues/11 issue and I've spent whole day investigating fetching methods from MagicalRecord. So, currently, fetch method from JSQCoreDataKit
public func fetch<T:NSManagedObject>(#request: FetchRequest<T>, inContext context: NSManagedObjectContext) -> FetchResult<T> 

is something very close to this from MagicalRecord

NSPredicate *peopleFilter = [NSPredicate predicateWithFormat:@"Department IN %@", departments];
NSFetchRequest *peopleRequest = [Person MR_requestAllWithPredicate:peopleFilter];
[peopleRequest setReturnsDistinctResults:NO];
[peopleRequest setReturnPropertiesNamed:@[@"FirstName", @"LastName"]];
NSArray *people = [Person MR_executeFetchRequest:peopleRequest];

and I'm not sure that it's really necessary to implement other fetching methods from MagicalRecord, because you can customize  #request: FetchRequest<T>'s  predicate property for any purpose. 
It'll be great if you have any ideas how to improve fetching methods for JSQCoreDataKit.

**Comment by jessesquires** [comment]
Thanks @artemkalinovsky !

I opened this issue for this kind of investigation and discussion. I didn't really have anything specific in mind.

I'm building out the features of `JSQCoreDataKit` as I'm using it in some side projects.

Also, in general, if you have any feature ideas — please open an issue anytime! :smile:

**Comment by jessesquires** [comment]
Closing this based on comments above.

Sounds like maybe a predicate builder might be useful in the future instead.
