### ISSUE TITLE
Crash on fetch request

### ISSUE THREAD

**Issue by Alexey-Matjuk** [jessesquires/JSQCoreDataKit#37]
I'm not sure if I'm missing something but my app crashes on fetch request. Because it can't find
`initWithEntity:insertIntoManagedObjectContext:` initialiser. I implemented my managed object same way as in the examples:
```
final class User: NSManagedObject {
    
    init(context: NSManagedObjectContext, ...) {
            let entity = NSEntityDescription.entityForName(self.dynamicType.modelName, inManagedObjectContext: context)!
            super.init(entity: entity, insertIntoManagedObjectContext: context)
            ...
    }

}
```
To fix this issue I changed the implementation:
```
final class User: NSManagedObject {

    override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext?) {
        super.init(entity: entity, insertIntoManagedObjectContext: context)
    }

    convenience init(context: NSManagedObjectContext, ...) {
            let entity = NSEntityDescription.entityForName(self.dynamicType.modelName, inManagedObjectContext: context)!
            self.init(entity: entity, insertIntoManagedObjectContext: context)
            ...
    }

}
```
Is there other way to fix this issue? Because overriding initialiser for every managed object looks not very clean

**Comment by jessesquires** [comment]
Hey @Alexey-Matjuk :smile: 

Unfortunately, overriding `init(entity: insertIntoManagedObjectContext context:)` is necessary because of how Core Data works under the hood — which is all KVC/KVO. It doesn't know about designated initializers.

However, you can make it `@objc private` so that the rest of your Swift code can only use the designated init.

I'm in the process of updating the examples:
https://github.com/jessesquires/JSQCoreDataKit/blob/develop/ExampleModel/ExampleModel/Company.swift
