### ISSUE TITLE
Forced unwrapping in entity()

### ISSUE THREAD

**Issue by VladislavJevremovic** [jessesquires/JSQCoreDataKit#54]
Hello @jessesquires :smile:, a quick question:

Regarding forced unwrapping of `NSEntityDescription.entityForName()` in `CoreDataExtensions.swift`: why shouldn't the optional be passed on?

Thanks for your time :+1:

**Comment by jessesquires** [comment]
Hey @VladislavJevremovic :smile: 

This is mostly a design/style choice. 

The only reason this is optional is because of ObjC and "stringly typing". If you mistype the `entityName` string, then this operation can fail.

In practice, this shouldn't ever fail — except for during development if you've made a typo, and in that case you'll want to crash and simply fix the typo.

Returning a non-optional here makes the reset of your code cleaner.

Hope that helps!
